name: Build

on:
  pull_request:
  push:
    branches:
      - '**'
    paths-ignore:
      - 'README.md'
      - '.github/FUNDING.yml'
      - '.github/ISSUE_TEMPLATE/**'

permissions:
  contents: read

jobs:
  build:
    name: Build & Run tests
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Free up disk space in runner
        uses: ./.github/actions/disk-cleanup

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: 'https://gradle.com/terms-of-service'
          build-scan-terms-of-use-agree: 'yes'

      - name: Enable KVM
        run: |
          sudo tee /etc/udev/rules.d/99-kvm4all.rules >/dev/null <<EOF
          KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"
          EOF
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Extract library version info
        id: meta
        run: |
          version=$(awk -F'"' '/^version\s*=/{print $2}' lib/android/build.gradle.kts)
          echo "version=v$version" >> $GITHUB_OUTPUT

      - name: Compile modules
        run: ./gradlew assemble --scan

      - name: Run unit tests
        run: ./gradlew check

      - name: Run instrumented tests on emulator
        run: ./gradlew ciGroupDebugAndroidTest

      - name: Publish Snapshot
        if: "github.ref_name == 'main' && endsWith(steps.meta.outputs.version, 'SNAPSHOT')"
        run: ./gradlew publishToMavenCentral
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_PASSWORD }}
