name: Snapshot Release

on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed
    branches:
      - main

permissions:
  contents: read

jobs:
  publish_snapshot:
    name: Publish Snapshot to Maven Central
    runs-on: ubuntu-24.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Extract library version info
        id: version
        run: |
          version=$(awk -F'"' '/^version\s*=/{print $2}' lib/android/build.gradle.kts)
          echo "version=v$version" >> $GITHUB_OUTPUT

      - name: Publish Snapshot
        if: "endsWith(steps.version.outputs.version, 'SNAPSHOT')"
        run: ./gradlew publishToMavenCentral
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_PASSWORD }}
