name: Test

on:
  pull_request:
  push:
    branches:
      - '**'
    paths-ignore:
      - 'README.md'
      - '.github/FUNDING.yml'
      - '.github/ISSUE_TEMPLATE/**'

permissions:
  contents: read

jobs:
  wrapper_validation:
    name: Validate Gradle wrapper
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Run wrapper validation
        uses: gradle/actions/wrapper-validation@v3

  test:
    name: Run tests
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Run tests
        run: ./gradlew build --no-daemon
