name: Test

on:
  pull_request:
  push:
    branches:
      - '**'
    paths-ignore:
      - 'README.md'
      - '.github/FUNDING.yml'
      - '.github/ISSUE_TEMPLATE/**'

permissions:
  contents: read

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: 'https://gradle.com/terms-of-service'
          build-scan-terms-of-use-agree: 'yes'

      - name: Accept Android SDK licenses
        run: yes | "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" --licenses

      - name: Compile modules
        run: ./gradlew assemble --scan

      - name: Run unit tests
        run: ./gradlew check

      - name: Run instrumented tests on emulator
        run: ./gradlew ciGroupDebugAndroidTest
